### ISSUE TITLE
>> instead of > for input

### ISSUE THREAD

**Issue by goingtosleep** [0101/pipetools#12]
I don't know if it's possible to change `>` to `>>` for the input method? IMO `>>` is less used, especially in numerical / science-related code. I looked around the source code but didn't find where to make the change (I don't see `__gt__` method in `Pipe` class). 

Thank you.

**Comment by 0101** [comment]
Unfortunately that's not possible because of [operator precedence](https://docs.python.org/3.7/reference/expressions.html#operator-precedence). `>>` binds stronger than `|`, so `input >> func1 | func2` would be evaluated as `(input >> func1) | func2`, so you'd have to always put parentheses around the piping composition - and face possibly confusing errors when you forget. 

If using `>` for input is making your code confusing, I recommend naming your composed functions and then just calling them the usual way:
```python
my_func = dothis | dothat | etc
my_func(input)
```
